### ISSUE TITLE
start network

### ISSUE THREAD

**Issue by tony-armstrong** [b2network/b2-node#20]
1. adjust b2-zkevm-node conf(contract, ip, port, etc.) to adapt to b2-node
2. adjust b2-zkevm-node genesis(contract, ip, port, etc.) to adapt to b2-node

**Comment by tony-armstrong** [comment]
The Full Prover require 96-core CPU, Mininum 768GB RAM [Deploying Your Own Full zkEVM | Polygon Wiki](https://wiki.polygon.technology/docs/zkevm/deploy-fullzkevm/#computing-requirements)

**Comment by tony-armstrong** [comment]
1. the local dev/test (mock prover) network can be started
2. should deployment-related code/doc be moved to repo b2network/b2-deployment?  b2network/b2-deployment#1 @0x677261706562616261

**Comment by 0x677261706562616261** [comment]
> 1. the local dev/test (mock prover) network can be started
> 2. should deployment-related code/doc be moved to repo b2network/b2-deployment?  [Init b2 network devnet scripts b2-deployment#1](https://github.com/b2network/b2-deployment/issues/1) @0x677261706562616261

If not so many deps exist, i think it is better to moving. what's your opinion? Maybe we could have a call tomorrow.

**Comment by tony-armstrong** [comment]
1. some e2e test actions rely on these codes
    ```bash
    intel-10400f .github gigit remote get-url origin 
    git@github.com:b2network/b2-zkevm-node.git
    intel-10400f .github git:(develop) grep -wrnE 'make|test' workflows/test-*
    workflows/test-e2e.yml:14:  test-e2e:
    workflows/test-e2e.yml:34:      run: make build-docker
    workflows/test-e2e.yml:37:      run: make compile-scs
    workflows/test-e2e.yml:38:      working-directory: test
    workflows/test-e2e.yml:41:      run: make test-e2e-group-${{ matrix.e2e-group }}
    workflows/test-e2e.yml:42:      working-directory: test
    workflows/test-from-prover.yml:15:  test-from-prover:
    workflows/test-from-prover.yml:44:      run: make build-docker
    workflows/test-from-prover.yml:47:      run: make compile-scs
    workflows/test-from-prover.yml:48:      working-directory: test
    workflows/test-from-prover.yml:51:      run: make test-full-non-e2e
    workflows/test-from-prover.yml:52:      working-directory: test
    workflows/test-full-non-e2e.yml:14:  test-full-non-e2e:
    workflows/test-full-non-e2e.yml:32:      run: make compile-scs
    workflows/test-full-non-e2e.yml:33:      working-directory: test
    workflows/test-full-non-e2e.yml:38:      run: make test-full-non-e2e
    workflows/test-full-non-e2e.yml:39:      working-directory: test
    ```
1. I think even if this part is moved to another repo, there is still a way to be used by action
2. or maybe wo can leave it alone and let the bullets fly for a while 😄

how about we not move this code yet?  @0x677261706562616261 @Stonepapa

**Comment by tony-armstrong** [comment]
b2network/b2-zkevm-node#7
