### ISSUE TITLE
Investigate Storm DS

### ISSUE THREAD

**Issue by 0x677261706562616261** [b2network/b2-node#25]
Investigate https://github.com/Storm-WG

- run the node 
- check the read and write API is available

**Comment by robertcc0410** [comment]
Compilation failed, the dependent library could not be compiled successfully, miniscript: https://github.com/rust-lang/rust/issues/110475

**Comment by robertcc0410** [comment]
refer: https://github.com/rust-bitcoin/rust-miniscript/issues/549

**Comment by 0x677261706562616261** [comment]
> refer: [rust-bitcoin/rust-miniscript#549](https://github.com/rust-bitcoin/rust-miniscript/issues/549)

so it can't work,right? @robertcc0410

**Comment by robertcc0410** [comment]
> > refer: [rust-bitcoin/rust-miniscript#549](https://github.com/rust-bitcoin/rust-miniscript/issues/549)
> 
> so it can't work,right? @robertcc0410

yes, you can lower your rust version to v1.59.0 and it will compile successfully

**Comment by robertcc0410** [comment]
this storage cannot be used without detailed documentation
