### ISSUE TITLE
bitcoin-indexer and bitcoin-state-generator

### ISSUE THREAD

**Issue by 0x677261706562616261** [b2network/b2-node#3]
- Q1: Why bitcoin data need from b2 chain to rollup instead directly from bitcoin to rollup? by @tony-armstrong 
- Q2: How generate zk proof in the bitcoin-indexer unless we use evm to do this and make a prover also in b2 chain?
@Stonepapa

**Comment by Stonepapa** [comment]
refer to unisat opensource indexer: https://github.com/unisat-wallet/libbrc20-indexer

**Comment by 0x677261706562616261** [comment]
track the by #22
