### ISSUE TITLE
Actions Failure 

### ISSUE THREAD

**Issue by oxf71** [b2network/b2-node#8]
There are several actions that fail because of permission

* https://github.com/b2network/b2-node/actions/runs/6704803633
* https://github.com/b2network/b2-node/actions/runs/6704803657
* https://github.com/b2network/b2-node/actions/runs/6704974140

**Comment by oxf71** [comment]
Settings -> Actions -> Gereral Workflow permissions 


![WeChat6cfaeab8b21be20d92df8345a9a69e4c](https://github.com/b2network/b2-node/assets/144757737/d865d3bb-98a6-4d41-b7ed-71938a8fc463)

**Comment by 0x677261706562616261** [comment]
@oxf71 setted.

**Comment by oxf71** [comment]
@0x677261706562616261 same problem

failure:

https://github.com/b2network/b2-node/actions/runs/6729603869/job/18323562016



normal:

https://github.com/oxf71/b2-node/actions/runs/6733450831/job/18302170162?pr=8

**Comment by oxf71** [comment]
`Pull Request Labeler` actions try use `pull_request_target` replace `pull_request`

https://github.com/actions/labeler#permissions

**Comment by oxf71** [comment]
done
